services:
  - type: web
    name: apextrades-backend
    runtime: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: apextrades61@gmail.com
      - key: EMAIL_PASSWORD
        value: lonp ycrf tebs ldjl
      - key: FRONTEND_URL
        value: https://apextradesv2.vercel.app
    # Add this if your backend is in a subdirectory
    rootDirectory: backend

databases:
  - name: apextrades-db
    plan: free
    databaseName: apextrades
    user: apextrades_user